# Generated by Django 5.1.5 on 2025-05-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='password_confirmation',
            new_name='password2',
        ),
    ]
