# Generated by Django 5.1.5 on 2025-05-11 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_rename_password_register_password1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
