# Generated by Django 5.1.5 on 2025-06-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'ارتباط باما', 'verbose_name_plural': 'ارتباط باما'},
        ),
    ]
