# Generated by Django 5.1.5 on 2025-07-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
