# Generated by Django 5.1.5 on 2025-07-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
