# Generated by Django 5.1.5 on 2025-07-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
