# Generated by Django 5.1.5 on 2025-07-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='کاربر', max_length=80, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='سیستم', max_length=80, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='user',
            name='post_code',
            field=models.CharField(default='0000000000', max_length=10, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='user',
            name='real_address',
            field=models.CharField(default='نامشخص', max_length=400, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='تلفن همراه'),
        ),
    ]
