# Generated by Django 5.1.5 on 2025-04-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=100)),
                ('P_image', models.ImageField(upload_to='media/images/')),
            ],
        ),
    ]
