# Generated by Django 5.1.5 on 2025-04-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_slider',
            name='P_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
