# Generated by Django 5.1.5 on 2025-05-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_slider_delete_product_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='link',
        ),
    ]
