# Generated by Django 5.1.5 on 2025-06-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_slider_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلاید', 'verbose_name_plural': 'اسلایدر'},
        ),
    ]
