# Generated by Django 5.1.5 on 2025-09-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_slider_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='category',
        ),
    ]
