# Generated by Django 5.1.5 on 2025-09-03 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_remove_slider_category'),
        ('Products', '0026_remove_products_is_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='category',
            field=models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_category', to='Products.categories'),
        ),
    ]
