# Generated by Django 5.1.5 on 2025-08-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('discount', models.PositiveIntegerField(max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
