# Generated by Django 5.1.5 on 2025-08-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_discountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='discount',
            field=models.PositiveIntegerField(),
        ),
    ]
