# Generated by Django 5.1.5 on 2025-08-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_alter_discountcode_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcode',
            options={'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کد های تخفیف'},
        ),
    ]
