# Generated by Django 5.1.5 on 2025-08-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_alter_discountcode_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
