# Generated by Django 5.1.5 on 2025-05-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
