# Generated by Django 5.1.5 on 2025-05-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_alter_products_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
    ]
