# Generated by Django 5.1.5 on 2025-05-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_products_is_bestseller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discount_percent',
        ),
    ]
