# Generated by Django 5.1.5 on 2025-05-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_remove_products_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
