# Generated by Django 5.1.5 on 2025-05-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_products_discount_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='is_featured',
            new_name='is_offer',
        ),
        migrations.AddField(
            model_name='products',
            name='offer_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
