# Generated by Django 5.1.5 on 2025-05-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_rename_is_featured_products_is_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='birthplace',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='breed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='caffeine_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='make_with',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
