# Generated by Django 5.1.5 on 2025-05-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_products_birthplace_products_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
