# Generated by Django 5.1.5 on 2025-05-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_products_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='slug',
        ),
    ]
