# Generated by Django 5.1.5 on 2025-06-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_alter_products_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-created_at']},
        ),
    ]
