# Generated by Django 5.1.5 on 2025-07-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0020_commentvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentVote',
        ),
    ]
