# Generated by Django 5.1.5 on 2025-07-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0021_delete_commentvote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظر ها'},
        ),
    ]
