# Generated by Django 5.1.5 on 2025-08-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0024_alter_products_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discount_price',
        ),
    ]
