# Generated by Django 5.1.5 on 2025-08-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0025_remove_products_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='is_offer',
        ),
        migrations.RemoveField(
            model_name='products',
            name='offer_expiration',
        ),
    ]
